### ISSUE TITLE
update imaging flow cytometry website

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/cellprofiler.github.com#101]
The CP imaging flow cytometry website 
https://cp-website.github.io/imaging-flow-cytometry/
needs to be updated with the latest streamlined workflow from our 2016 Methods paper. I'll send a pull request when done..

**Comment by N3llz** [comment]
Rather, @holgerhennig should update: http://cellprofiler.org/imagingflowcytometry/index.html 
And I will update the link in the tutorials page to go to http://cellprofiler.org/imagingflowcytometry/index.html rather than https://cp-website.github.io/imaging-flow-cytometry/

**Comment by N3llz** [comment]
#102 addresses the redirect needed

**Comment by holgerhennig** [comment]
Thanks Jeanelle, will do :)
