### ISSUE TITLE
Make search bar more subtle

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/cellprofiler.github.com#11]
The search bar is fairly large and prominent making it look like a page heading. My best bet is that it would be more subtle and nicer-looking but still findable if located at the bottom of the left-hand table of contents (i.e., below the twitter/FB icons), but others may have better ideas.

![search](https://cloud.githubusercontent.com/assets/1213811/18929997/551008f4-8594-11e6-819d-0653d2b67e0b.jpg)

**Comment by AnneCarpenter** [comment]
This would also solve the problem of the search bar not being available on the main cellprofiler.org page, which is the most likely place someone would want to use it.

**Comment by bledford87** [comment]
Obsolete now that we've migrated to OpenScholar.
