### ISSUE TITLE
Dates in releases page

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/cellprofiler.github.com#111]
The date seems to be hard coded. Can we make it update automatically?https://github.com/CellProfiler/cellprofiler.github.com/blob/master/releases/index.html#L176

**Comment by N3llz** [comment]
Great question... @mcquin @0x00b1 Do you have any idea about this?

**Comment by AnneCarpenter** [comment]
Related to https://github.com/CellProfiler/CellProfiler/issues/2552

**Comment by N3llz** [comment]
We got rid of dates during a previous update
