### ISSUE TITLE
Add Orbit to Software Interface page

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/cellprofiler.github.com#113]

**Comment by N3llz** [comment]
@bethac07 We also need a small description and the interface. If you want to write these, you can send them to me and I'll include them when I update this page. @AnneCarpenter may want to contribute thoughts/opinions as well

**Comment by bethac07** [comment]
@AnneCarpenter and I propose

Description:
Orbit is an open source image analysis program designed to operate on stitched images and tissue sections.  It is designed to run on an Omero image server but can also be used on local images.
Interface:
Orbit can be used to specify a region of interest in a very large image (e.g. a whole-slide scan), and can then send tiled sub-regions to CellProfiler for high-throughput processing of individual cells in each tile.

(Website is here: http://www.orbit.bio/)

**Comment by AnneCarpenter** [comment]
Updated after input from Manuel Stritt:
Description:
Orbit Image Analysis is open source software for quantifying large-format images such as whole slide scans of tissue. It can load images from local disk or connect to an Omero image server and can process images on a local computer or on a cluster using Spark.

Interface:
Orbit can be used to specify a region of interest in a very large image (e.g. a whole-slide scan), and can then send tiled sub-regions to CellProfiler for high-throughput processing of individual cells in each tile. All tiles in the valid ROI are processed via CellProfiler, the results are read back into Orbit and can be visualized.
