### ISSUE TITLE
CPAnalyst Windows nightly is old

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/cellprofiler.github.com#12]
Nice new web page!

But the CPA Windows nightly (still?) points to http://d1zymp9ayga15t.cloudfront.net/CellProfiler-Analyst-nightly.exe which, looking at S3, points to an .exe that is dated 5/27/2016.

Side note: The S3 bucket is messy.  There are releases in the root folder, in the /releases folder, and in /releases/2.X.X.

**Comment by N3llz** [comment]
http://d1zymp9ayga15t.cloudfront.net/CellProfiler-Analyst-nightly.exe is always the latest.

@daviddao and @jhung0 has their been a nightly release since 5/27/2016? If not, would you like me to file an issue on the CellProfiler-Analyst repository?

**Comment by N3llz** [comment]
@dlogan The S3 bucket is a total mess! I'll file a new issue.

**Comment by N3llz** [comment]
#20

**Comment by dlogan** [comment]
Oh, I assumed that since the Mac release date was so much more recent, that the Windows version was not as up to date:
![image](https://cloud.githubusercontent.com/assets/1225595/18963326/88700ccc-8642-11e6-8559-5fefe46debe5.png)

And I sincerely hope I didn't contribute in the past to the mess!

**Comment by jhung0** [comment]
There seems to be constant problems with the build, but I have no idea why/when/what to do about it.

**Comment by daviddao** [comment]
Normally jenkins automatically updates de S3 bin. I think you can try to check jenkins on windows (our windows build machine). It might be that the automatic build just fails since 5/27/2016 (which would be crazy).

**Comment by 0x00b1** [comment]
Do we still have a Windows build machine? 😳

I know CellProfiler has not had a successful nightly build for months.

**Comment by daviddao** [comment]
Actually I don't know. I was assuming the build machine exists (isn't it in our collaborator room?).
If not, that would explain everything!
