### ISSUE TITLE
delete http://cellprofiler.org/CellProfiler-Analyst/

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/cellprofiler.github.com#127]
I google'd something about CPA and this page came up
http://cellprofiler.org/CellProfiler-Analyst/
which is some badly formatted documentation.

The new CPA docs are here afaik http://cellprofiler.org/cpa/ and so it seems like the other one should be deleted.

Similar to #85

**Comment by AnneCarpenter** [comment]
Thanks for bringing it to our attention!

**Comment by N3llz** [comment]
Thanks David, we resolved this at some point but I didn't close out this issue it seems
