### ISSUE TITLE
add side by side images on examples page

### ISSUE THREAD

**Issue by N3llz** [CellProfiler/cellprofiler.github.com#129]
The images on the examples page used to flip back and forth between the original and the corrected version when you would hover over them. The javascript was taken out and needs to be added back in. 
Likely something like this: 
```
$('#ExampleID').hover(function() {
  $(this).attr('src', 'http://someimagesource_Corrected.png');
}, function() {
  $(this).attr('src', 'http://someimagesource_Original.png');
});

```
and then the html:
```
<img alt="some text"  id="ExampleID" name="ExampleName" src="http://someimagesource_Corrected.png"/>
```

**Comment by AnneCarpenter** [comment]
An alternative might be to make GIFs, if that is easier.

**Comment by N3llz** [comment]
@AnneCarpenter I think I'm close with the javascript, but good idea to try the gifs. I just think they may be a little overwhelming to have all of the images flashing back and forth on the page at once - I'll test it out!

**Comment by N3llz** [comment]
We decided to just add both images side by side rather than have a bunch of flashing gifs
