### ISSUE TITLE
Line spacing issues on the examples page

### ISSUE THREAD

**Issue by pawni** [CellProfiler/cellprofiler.github.com#14]
On Mac OS X 10.11.6 with Safari 9.1.3 the examples page looks like this:
<img width="990" alt="screen shot 2016-09-29 at 11 09 12" src="https://cloud.githubusercontent.com/assets/2412413/18949988/a1261bf6-8635-11e6-99e0-f1dd073893d9.png">

**Comment by pawni** [comment]
Is this a duplicate of #1 / #6 ?

**Comment by mcquin** [comment]
Unclear. #1 is closed but #2 is unmerged. I see this too on Safari. Looks fine on FireFox. I haven't checked on Chrome or Internet Explorer.

**Comment by N3llz** [comment]
Allen fixed this a while ago
