### ISSUE TITLE
add BSD-3 license mention on releases page

### ISSUE THREAD

**Issue by N3llz** [CellProfiler/cellprofiler.github.com#142]
Add "(BSD-3 license)" below CP name on releases page

**Comment by N3llz** [comment]
@0x00b1 said we intentionally do not want this, so closing the issue. (FYI @AnneCarpenter)

**Comment by AnneCarpenter** [comment]
I think this spawned from people thinking the information needed to be more obvious - in particular, people from companies going to the CP site and not knowing what license it's under. @0x00b1 do you mind explaining the rationale?
