### ISSUE TITLE
Some link problems on the published pipeline page

### ISSUE THREAD

**Issue by braymp** [CellProfiler/cellprofiler.github.com#156]
Just a few:
- The Nieland paper DOI link doesn't work (which I happened to need at the time)
- The Du paper doesn't have a DOI at all.
- The Logan 2015 and Jolly papers have an incorrect DOI link (http://cellprofiler.org/examples/dx.doi.org/10.1016/j.ymeth.2015.12.002)
- The Barczak pubs should be moved up.

**Comment by AnneCarpenter** [comment]
Thanks for reporting!
