### ISSUE TITLE
add new 3.0 example pipelines page

### ISSUE THREAD

**Issue by N3llz** [CellProfiler/cellprofiler.github.com#159]
- archive /examples page: rename to /previous_examples and attach a huge link at the top saying These are old, please see new /examples page
- create new /examples page with the updated zip files for each pipeline
- make the old examples page look different/old so that people KNOW it's old

**Comment by AnneCarpenter** [comment]
Note that "These are old" should specify what version numbers they are good for.

**Comment by N3llz** [comment]
I was going to put "(Prior to 3.0)", or I can list the range if that's better

**Comment by AnneCarpenter** [comment]
Prior to 3.0 is perfect (since we don't know the exact range that works for each pipeline).
