### ISSUE TITLE
Disappearing menu bar

### ISSUE THREAD

**Issue by N3llz** [CellProfiler/cellprofiler.github.com#17]
When the browser window is small or you view the website on a tablet/ipad, the menu bar disappears and there doesn't seem to be a way to access it. Find a way to maybe make it a small button so that it opens and becomes visible.

**Comment by AnneCarpenter** [comment]
Confirmed on mobile (where there is no image on the home page either), but wow, otherwise the site looks surprisingly nice on a tiny screen!

**Comment by dlogan** [comment]
Was just about to post this.  Same here.  FYI - here's a screenshot from an Android device on Chrome:
![cellprofiler org_homepage_screenshot_20161006-150921](https://cloud.githubusercontent.com/assets/1225595/19167161/776c8bbc-8bd8-11e6-988c-a7bf12c86ff2.png)

**Comment by mcquin** [comment]
It's because of these lines: https://github.com/CellProfiler/cellprofiler.github.com/blob/master/PNAS2009/index.html#L58

**Comment by bledford87** [comment]
Obsolete since migrating to OpenScholar.
