### ISSUE TITLE
Manuals page should have 3.0 manual added as well

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/cellprofiler.github.com#179]
http://cellprofiler.org/manuals/ only has up to 2.2, we should have 3.0 as well

**Comment by N3llz** [comment]
There is a cellprofiler.org/manuals page that has the manuals up to 2.2, but not the new 3.0 manual (that you can find currently on the cellprofiler.org/releases page, located here - http://cellprofiler-manual.s3.amazonaws.com/CellProfiler-3.0.0/index.html).  

- [ ] Need to add version 3.0 to cellprofiler.org/manuals, with this link (http://cellprofiler-manual.s3.amazonaws.com/CellProfiler-3.0.0/index.html)
