### ISSUE TITLE
add MeioSeed published pipeline and update releases page

### ISSUE THREAD

**Issue by N3llz** [CellProfiler/cellprofiler.github.com#183]
* MeioSeed publication to published_pipelines page & include ccpipe and classifier files: [doi](https://doi.org/10.1186/s13007-018-0298-3) 
* from kyle: Apparently, a requirement to run CellProfiler on any OS is to have the Java Development Kit (JDK) installed and not the Java Runtime Environment (JRE). The current text on the webpage is causing confusion during the installation process and setting CP users up for installation errors. In addition, the Linux and Windows links point the download page of the JRE, yet the macOS link points to the JDK. All these links should be the same page (the macOS link) to download the JDK 8 installer. 
1. Update to make one big button listing all three 
2. change text to be JDK 8 not JRE

**Comment by bethac07** [comment]
I think the idea was to update the download links in addition to just the text of JDK/JRE
