### ISSUE TITLE
CellProfiler 2 downloads are not available

### ISSUE THREAD

**Issue by shntnu** [CellProfiler/cellprofiler.github.com#198]
The links to download CellProfiler 2.* are broken

https://cellprofiler.org/previous_releases/

https://github.com/CellProfiler/cellprofiler.github.com/blob/master/_data/previous_releases.yml#L13-L46

**Comment by AnneCarpenter** [comment]
@rvale17 may be able to fix this together with @N3llz

**Comment by N3llz** [comment]
This was just due to a billing issue where we couldn't access our AWS assets. The links all work again now
