### ISSUE TITLE
Inform users that Java 8 is required on Downloads page

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/cellprofiler.github.com#211]
At the top of the Previous Releases page (https://cellprofiler.org/previous_releases/) it says "Note: CellProfiler versions 2.2 and 3.0 require Java 8".  

IMHO I think that this guidance ought to be on the main Downloads page too (https://cellprofiler.org/releases/)

**Comment by bledford87** [comment]
Obsolete with new site layout since migrating to OpenScholar.
