### ISSUE TITLE
use Jekyll to build website

### ISSUE THREAD

**Issue by N3llz** [CellProfiler/cellprofiler.github.com#25]
We need to use Jekyll for redirects. It would also be nice to extract the navigation into a template.

**Comment by mcquin** [comment]
[ ] Create a default layout for pages #59

**Comment by N3llz** [comment]
@mcquin is this issue closed? #59 takes over from here correct?

**Comment by mcquin** [comment]
@N3llz no, #59 is a sub-issue for this.

**Comment by N3llz** [comment]
oh, never mind @mcquin , i mistook this for the old issue of just adding jekyll. Gotcha

**Comment by bledford87** [comment]
Obsolete now that we've migrated to OpenScholar.
