### ISSUE TITLE
'Previous releases' link on release page goes to dead page

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/cellprofiler.github.com#26]
Not sure if it's a dead page or dead link

**Comment by N3llz** [comment]
wrong link: currently links to http://cellprofiler.org/previousReleases.html and it should link to http://cellprofiler.org/previousReleases/

**Comment by N3llz** [comment]
I'm going to change this location back to http://cellprofiler.org/previousReleases.html because it seems like that's where it used to live... Can anyone confirm this or have any additional input?
