### ISSUE TITLE
404 after update

### ISSUE THREAD

**Issue by braymp** [CellProfiler/cellprofiler.github.com#32]
Just noticed today that cp.org updated; looks nice! However, some pages return 404's:
* http://cellprofiler.org/previousReleases.html
* http://cellprofiler.org/examples/published_pipelines.html
* http://cellprofiler.org/imagingflowcytometry/

I'm sure there are others...

**Comment by mcquin** [comment]
Related to #10

**Comment by AnneCarpenter** [comment]
Same for 
http://cellprofiler.org/tutorials.html
http://cellprofiler.org/examples.html

Both of which are embedded in CellProfiler's welcome screen so even changing the URLs there doesn't help people using existing versions of CP.

**Comment by mcquin** [comment]
Filed as separate issues for easier tracking:

https://github.com/CellProfiler/cellprofiler.github.com/issues/42
https://github.com/CellProfiler/cellprofiler.github.com/issues/43
