### ISSUE TITLE
Page with instructions for installing on CentOS no longer exists

### ISSUE THREAD

**Issue by N3llz** [CellProfiler/cellprofiler.github.com#36]
from https://github.com/CellProfiler/CellProfiler/issues/2383

**Comment by N3llz** [comment]
@AnneCarpenter It looks like the [releases page](http://cellprofiler.org/releases/) has been updated since the Linux download option has links to [the install instructions on our wiki](https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Linux%29) 
I'll close the issue if this is done. (btw, did [allen's instructions](https://github.com/CellProfiler/CellProfiler/issues/2383#issuecomment-251642904) end up getting added to the github page? Lmk if this item still needs action.

**Comment by AnneCarpenter** [comment]
I think the task here is to redirect http://cellprofiler.org/linux.html to go to here:
https://github.com/CellProfiler/CellProfiler/wiki

From there, people can located the version of linux they need.
