### ISSUE TITLE
Missing URL: http://cellprofiler.org/ExampleFlyImages/ExampleFlyURL.cppipe

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/cellprofiler.github.com#37]
Required for CellProfiler example pipeline. See: https://github.com/CellProfiler/CellProfiler/issues/2385 .

It would be best to host the file at the same URL. If that proves difficult, please update https://github.com/CellProfiler/CellProfiler/issues/2385 with the correct URL and we can update it in CP.

[ExampleFlyUrl.cppipe](https://github.com/CellProfiler/cellprofiler.github.com-backup/blob/ba6c54ab974d4dbdb70fd38f610ef7e620a288d3/ExampleFlyImages/ExampleFlyURL.cppipe)

**Comment by mcquin** [comment]
Another reason to preserve original URL: we won't need to release CP to fix users. :)

**Comment by AnneCarpenter** [comment]
Unfortunately, you will also need to put the proper images in proper place too: 
http://cellprofiler.org/ExampleFlyImages/ should contain these images
<img width="263" alt="imagesmissing" src="https://cloud.githubusercontent.com/assets/1213811/19118595/def96f96-8aea-11e6-9189-82f3051af77e.png">

**Comment by AnneCarpenter** [comment]
Claire properly opened a separate issue #40 , closing this
