### ISSUE TITLE
Redirect from /download to /releases

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/cellprofiler.github.com#69]
@braymp pointed out in #68  that http://cellprofiler.org/download/ goes to an old 2.1.1 page. That page should be deleted and http://cellprofiler.org/download redirected to http://cellprofiler.org/releases

**Comment by braymp** [comment]
Please do #54 before this one, since I'll soon running workshop and would like to them to this page, if the other one is not fixed in time.
