### ISSUE TITLE
mask url home base name

### ISSUE THREAD

**Issue by N3llz** [CellProfiler/cellprofiler.github.com#71]
Is it possible to replace d1zymp9ayga15t.cloudfront.net with cellprofiler.org somehow?

@mcquin @0x00b1 do either of you know how to do this? or if it's possible?

![temp](https://cloud.githubusercontent.com/assets/20823196/19818923/089c5420-9d20-11e6-91e5-7d9d1f2f24a0.jpg)

**Comment by mcquin** [comment]
No. I don't believe there is.
