### ISSUE TITLE
add 2016 cell painting and hackathon entry to press page

### ISSUE THREAD

**Issue by N3llz** [CellProfiler/cellprofiler.github.com#74]
http://cellprofiler.org/press.html
Add entry for 2016 (pink marker): Science talks to Anne Carpenter about Cell Painting and the cytomining hackathon

**Comment by N3llz** [comment]
@AnneCarpenter You were referring to this article, correct?
http://science.sciencemag.org/content/352/6288/877.full

**Comment by AnneCarpenter** [comment]
Yes!
