### ISSUE TITLE
Source code installation instructions go to empty wiki page.

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/cellprofiler.github.com#86]

**Comment by bethac07** [comment]
Looks like there isn't a single source installation page, but rather one for each OS- do we want to make a central splash page for all of them, or just point people to the main Github page/main wiki page?

**Comment by AnneCarpenter** [comment]
Holy smokes! I deleted that page just a couple of hours ago. Impressive how quickly this was found! Nicely done.

Best to have all the "Source" buttons on this page:
http://cellprofiler.org/releases/

go here: 
https://github.com/CellProfiler/CellProfiler/wiki

That way we needn't worry about keeping a central list of source code installation instructions up to date (beyond the side bar on this home page).

**Comment by N3llz** [comment]
The CPA source buttons say "Download" and go to https://github.com/CellProfiler/CellProfiler-Analyst ... Should we update these to link to the Instructions as well? (https://github.com/CellProfiler/CellProfiler/wiki#source)
