### ISSUE TITLE
Link in online manual is broken

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/cellprofiler.github.com#88]
On the html CP manual page (http://d1zymp9ayga15t.cloudfront.net/CPmanual/index.html), there is a link near the top that is broken:

> This manual accompanies version 2014-07-23T17:45:00 6c2d896 of CellProfiler. The most recent manual is available [here](http://www.cellprofiler.org/CPmanual/).

**Comment by mcquin** [comment]
We should deprecate this manual (only provide a PDF version) and upload a 2.2 manual (with the correct URL).

**Comment by mcquin** [comment]
We should also ensure the link in the PDF is updated.
