### ISSUE TITLE
Example pipelines/tutorials cannot be downloaded

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/cellprofiler.github.com#99]
Help! Both myself and a forum user by DM report this...

Clicking links like these:
http://d1zymp9ayga15t.cloudfront.net/papers/85-Bray_CurrentProtocols_2015.pdf
http://d1zymp9ayga15t.cloudfront.net/content/Examplezips/ExampleYeastColonies_BT_Images.zip

from this page:
http://cellprofiler.org/examples

yields this error:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>299A01EFCC7CB2FD</RequestId>
<HostId>
kXpWGkQ+nqT+RFWCIwE4mnRwJpVRWS6LdQAeB1zNHpgR1xlBkYqrIxRETMRGqSdBHjtJrqClsU4=
</HostId>
</Error>

**Comment by 0x00b1** [comment]
Fixed. There was an overdue bill. I guess I should create a new issue for that?
